version: "3.8"

services:
  app:
    build:
      context: .
    container_name: black_widow_users
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    env_file: ./.env
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
    ports:
      - "8001:8001"
