version: "3.8"

services:
  app:
    build:
      context: .
    container_name: black_widow_users
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
    ports:
      - "8001:8001"
